// Generated by Jinja2 CLI. Do not manually edit.
resource "aws_iam_user" "fred_flintstone" {
  name = "fred-flintstone"
  path = "/"
}

resource "aws_iam_user" "wilma_flintstone" {
  name = "wilma-flintstone"
  path = "/"
}

resource "aws_iam_user" "pebbles_flintstone" {
  name = "pebbles-flintstone"
  path = "/"
}

resource "aws_iam_user" "barney_rubble" {
  name = "barney-rubble"
  path = "/"
}

resource "aws_iam_user" "betty_rubble" {
  name = "betty-rubble"
  path = "/"
}

resource "aws_iam_user" "bammbamm_rubble" {
  name = "bammbamm-rubble"
  path = "/"
}
