// Generated by Jinja2 CLI. Do not manually edit.
resource "aws_iam_group" "admin" {
  name = "admin"
  path = "/"
}

resource "aws_iam_group" "dev" {
  name = "dev"
  path = "/"
}

resource "aws_iam_group" "qa" {
  name = "qa"
  path = "/"
}
